Do not log OperationCanceledException on user cancel (fixes #65)
eclipse-platform/eclipse.platform.text pull request #73
Opened 2022-08-09 16:18 UTC by jukzi

Avoids "Unhandled event loop exception" log entry.

2022-08-09 16:18 UTC, jukzi commented
@iloveeclipse please try this. - works for me (windows).

2022-08-09 16:27 UTC, iloveeclipse commented
Well, if that really works on Windows, we can merge that. For me on RHEL 7.9 / GTK 3.22 it fixes the "unhandled event loop error" only, but the original issue is still there. Since that restores the status quo, we can take that.

2022-08-09 16:28 UTC, iloveeclipse commented
/rebase

2022-08-09 16:29 UTC, iloveeclipse commented
@jukzi : please rebase on master.

2022-08-09 16:33 UTC, iloveeclipse commented
> please rebase on master.

No need, there is a new button.

2022-08-09 16:35 UTC, iloveeclipse commented on org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/AbstractTextEditor.java
> +	@Override
```suggestion
```

2022-08-09 16:36 UTC, iloveeclipse requested changes
The extra Override is unrelated.

2022-08-09 16:57 UTC, iloveeclipse approved these changes
LGTM

2022-08-09 16:58 UTC, merged

2022-08-10 05:30 UTC, jukzi commented
Thanks Andrey for finalizing it.