.editorconfig
eclipse-platform/eclipse.platform.text pull request #90
Opened 2022-09-19 16:11 UTC by angelozerr

Signed-off-by: azerr <azerr@redhat.com>

2022-09-19 17:07 UTC, mickaelistria requested changes

2022-09-19 17:07 UTC, mickaelistria commented on org.eclipse.editorconfig/plugin.properties
> +pluginName=EditorConfig
```suggestion
pluginName=Support for editorconfig in Eclipse text editors
```

2022-09-19 17:07 UTC, mickaelistria commented on org.eclipse.editorconfig/plugin.xml
> +	       <startup class="org.eclipse.editorconfig.internal.EditorConfigStartup" />
I believe none of those are still necessary.

2022-09-19 17:07 UTC, mickaelistria commented on org.eclipse.editorconfig/src/org/eclipse/editorconfig/EditorConfigPlugin.java
> + *  http://www.eclipse.org/legal/epl-v10.html
Needs to be EPLv2

2022-09-19 17:07 UTC, mickaelistria commented on org.eclipse.editorconfig/src/org/eclipse/editorconfig/internal/EditorConfigPreferenceStoreAdapter.java
> +package org.eclipse.editorconfig.internal;
Missing copyright header.

2022-09-19 17:07 UTC, mickaelistria commented on org.eclipse.editorconfig/src/org/eclipse/editorconfig/internal/EditorTracker.java
> +public class EditorTracker implements IWindowListener, IPageListener, IPartListener {
Is this still necessary as the preferencestore is now provided as adapter?

2022-09-19 17:07 UTC, mickaelistria commented on org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/preferences/DocumentPreferenceStore.java
> +		// TODO Auto-generated method stub
We'll need all those todos to be fixed.

2022-09-19 20:05 UTC, angelozerr commented on org.eclipse.editorconfig/META-INF/MANIFEST.MF
> +Bundle-Version: 0.1.0.qualifier
fixed

2022-09-19 20:05 UTC, angelozerr commented on org.eclipse.editorconfig/META-INF/MANIFEST.MF
> +Bundle-SymbolicName: org.eclipse.editorconfig;singleton:=true
fixed

2022-10-21 15:55 UTC, sebthom commented
@angelozerr any specific reason why you added the ec4j jars to the git repo? would it not be better to reference the maven artifacts in the build target file and include them in the update site?

2022-10-21 16:00 UTC, angelozerr commented
> @angelozerr any specific reason why you added the ec4j jars to the git repo? would it not be better to reference the maven artifacts in the build target file and include them in the update site?

Indeed I should do that but I did that very quickly. I'm very busy with other features, but I will work on this PR again as soon as I will find time.

2023-05-18 12:18 UTC, angelozerr commented
Just for your information IJ uses ec4j https://github.com/search?q=repo%3AJetBrains%2Fintellij-community%20ec4j&type=code

2023-06-28 13:19 UTC, closed without merging